name: First Workflow

on: push

jobs: 
  build:
    runs-ons: ubuntu-latest
    
  steps:
    - uses: actions/checkout@v3
    
    - name: Running sample github checkout actions
    - run: echo "Github checkout actions run successfully"
    
